export const categoriesList = [
  {
    id: 1,
    categoryName: "vegetables",
    img: "../assets/images/vegetables.svg",
    ingredients: [
      "Beans",
      "Capsicum",
      "Broccoli",
      "Sprout",
      "Cabbage",
      "Lettuce",
      "Carrot",
      "Cauliflower",
      "Cucumber",
      "Eggplant",
      "Garlic",
      "Celery",
      "Kale",
      "Potato",
      "Onions",
      "Pumpkin",
      "Peas",
      "Corn",
      "Spinach",
      "Tomato",
      "Zucchini",
      "Yam",
      "Mushroom",
    ],
  },
  {
    id: 2,
    categoryName: "fruits",
    img: "../assets/images/fruits.svg",
    ingredients: [
      "Apple",
      "Banana",
      "Pear",
      "Orange",
      "Strawberry",
      "Cherry",
      "Grape",
      "Mango",
      "Blueberry",
      "Guava",
      "Plum",
      "Banana",
      "Raspberry",
      "Apricot",
      "Grapefruit",
      "Melon",
      "Coconut",
      "Peach",
      "Avocado",
      "Mandarin",
      "Jackfruit",
      "Papaya",
      "Kiwi",
      "Pineapple",
      "Lime",
    ],
  },
  {
    id: 3,
    categoryName: "dairy",
    img: "../assets/images/dairy.svg",
    ingredients: [
      "Milk",
      "Yogurt",
      "Cottage Cheese",
      "Mozzarella Cheese",
      "Butter",
      "Ice Cream",
      "Egg",
      "Cream",
      "Whipped Cream",
      "Ghee",
      "Brie",
      "Powdered Milk",
    ],
  },
  {
    id: 4,
    categoryName: "meat",
    img: "../assets/images/meat.svg",
    ingredients: [
      "Chicken Breast",
      "Bacon",
      "Ground Beef",
      "Sausage",
      "Steak",
      "Hot Dog",
      "Ham",
      "Turkey",
      "Pork",
      "Salami",
      "Tuna",
      "Salmon",
      "Fillet",
      "Sardines",
      "Cod",
      "Tilapia",
      "Shrimp",
    ],
  },
  {
    id: 5,
    categoryName: "vegetables",
    img: "../assets/images/vegetables.svg",
    ingredients: [
      "Beans",
      "Capsicum",
      "Broccoli",
      "Sprout",
      "Cabbage",
      "Lettuce",
      "Carrot",
      "Cauliflower",
      "Cucumber",
      "Eggplant",
      "Garlic",
      "Celery",
      "Kale",
      "Potato",
      "Onions",
      "Pumpkin",
      "Peas",
      "Corn",
      "Spinach",
      "Tomato",
      "Zucchini",
      "Yam",
      "Mushroom",
    ],
  },
  {
    id: 6,
    categoryName: "fruits",
    img: "../assets/images/fruits.svg",
    ingredients: [
      "Apple",
      "Banana",
      "Pear",
      "Orange",
      "Strawberry",
      "Cherry",
      "Grape",
      "Mango",
      "Blueberry",
      "Guava",
      "Plum",
      "Banana",
      "Raspberry",
      "Apricot",
      "Grapefruit",
      "Melon",
      "Coconut",
      "Peach",
      "Avocado",
      "Mandarin",
      "Jackfruit",
      "Papaya",
      "Kiwi",
      "Pineapple",
      "Lime",
    ],
  },
  {
    id: 7,
    categoryName: "dairy",
    img: "../assets/images/dairy.svg",
    ingredients: [
      "Milk",
      "Yogurt",
      "Cottage Cheese",
      "Mozzarella Cheese",
      "Butter",
      "Ice Cream",
      "Egg",
      "Cream",
      "Whipped Cream",
      "Ghee",
      "Brie",
      "Powdered Milk",
    ],
  },
  {
    id: 8,
    categoryName: "meat",
    img: "../assets/images/meat.svg",
    ingredients: [
      "Chicken Breast",
      "Bacon",
      "Ground Beef",
      "Sausage",
      "Steak",
      "Hot Dog",
      "Ham",
      "Turkey",
      "Pork",
      "Salami",
      "Tuna",
      "Salmon",
      "Fillet",
      "Sardines",
      "Cod",
      "Tilapia",
      "Shrimp",
    ],
  },
  {
    id: 9,
    categoryName: "vegetables",
    img: "../assets/images/vegetables.svg",
    ingredients: [
      "Beans",
      "Capsicum",
      "Broccoli",
      "Sprout",
      "Cabbage",
      "Lettuce",
      "Carrot",
      "Cauliflower",
      "Cucumber",
      "Eggplant",
      "Garlic",
      "Celery",
      "Kale",
      "Potato",
      "Onions",
      "Pumpkin",
      "Peas",
      "Corn",
      "Spinach",
      "Tomato",
      "Zucchini",
      "Yam",
      "Mushroom",
    ],
  },
];
