export const categoriesList = [
  {
    id: 1,
    categoryName: "Vegetables",
    img: "../assets/images/vegetables.svg",
    ingredients: [
      "Beans",
      "Capsicum",
      "Broccoli",
      "Sprout",
      "Cabbage",
      "Lettuce",
      "Carrot",
      "Cauliflower",
      "Cucumber",
      "Eggplant",
      "Garlic",
      "Celery",
      "Kale",
      "Potato",
      "Onions",
      "Pumpkin",
      "Peas",
      "Corn",
      "Spinach",
      "Tomato",
      "Zucchini",
      "Yam",
      "Mushroom",
    ],
  },
  {
    id: 2,
    categoryName: "Fruits",
    img: "../assets/images/fruits.svg",
    ingredients: [
      "Apple",
      "Banana",
      "Pear",
      "Orange",
      "Strawberry",
      "Cherry",
      "Grape",
      "Mango",
      "Blueberry",
      "Guava",
      "Plum",
      "Banana",
      "Raspberry",
      "Apricot",
      "Grapefruit",
      "Melon",
      "Coconut",
      "Peach",
      "Avocado",
      "Mandarin",
      "Jackfruit",
      "Papaya",
      "Kiwi",
      "Pineapple",
      "Lime",
    ],
  },
  {
    id: 3,
    categoryName: "Dairy",
    img: "../assets/images/dairy.svg",
    ingredients: [
      "Milk",
      "Yogurt",
      "Cottage Cheese",
      "Mozzarella Cheese",
      "Butter",
      "Ice Cream",
      "Egg",
      "Cream",
      "Whipped Cream",
      "Ghee",
      "Brie",
      "Powdered Milk",
    ],
  },
  {
    id: 4,
    categoryName: "Meat",
    img: "../assets/images/meat.svg",
    ingredients: [
      "Chicken Breast",
      "Bacon",
      "Ground Beef",
      "Sausage",
      "Steak",
      "Hot Dog",
      "Ham",
      "Turkey",
      "Pork",
      "Salami",
      "Tuna",
      "Salmon",
      "Fillet",
      "Sardines",
      "Cod",
      "Tilapia",
      "Shrimp",
    ],
  },
  {
    id: 5,
    categoryName: "Grains",
    img: "../assets/images/grain.svg",
    ingredients: [
      "Rice",
      "Brown Rice",
      "Barley",
      "Buckwheat",
      "Oatmeal",
      "Millets",
      "Popcorn",
      "Chia",
      "Quiona",
      "Chickpeas",
      "Lentils",
      "Peanuts",
      "Sunflower Seeds",
      "Flax Seeds",
      "Chana Dal",
    ],
  },
  {
    id: 6,
    categoryName: "Spices",
    img: "../assets/images/spice.svg",
    ingredients: [
      "Cinnamon",
      "Vanilla",
      "Paprika",
      "Garlic Powder",
      "Oregana",
      "Pepper",
      "Red Pepper Powder",
      "Thyme",
      "Onion Powder",
      "Bay Leaves",
      "Sage",
      "Turmeric",
      "Clove",
      "Peppercorns",
      "Taco Seasoning",
      "Nutmeg",
    ],
  },
  {
    id: 7,
    categoryName: "Sauces",
    img: "../assets/images/sauces.svg",
    ingredients: [
      "Mayonnaisse",
      "Ketchup",
      "Mustard",
      "Vinegar",
      "Soy Sauce",
      "Hot Sauce",
      "Salad Dressing",
      "Ranch",
      "Tahini",
      "Fish Sauce",
    ],
  },
  {
    id: 8,
    categoryName: "Baking",
    img: "../assets/images/bake.svg",
    ingredients: [
      "Flour",
      "Bread",
      "Baking Powder",
      "Baking Soda",
      "Yeast",
      "Cake Flour",
      "Cake Mix",
    ],
  },
  {
    id: 9,
    categoryName: "Miscellaneous",
    img: "../assets/images/misc.svg",
    ingredients: [
      "Corn Syrup",
      "Maple Syrup",
      "Sweetner",
      "Tofu",
      "Wine",
      "Beer",
      "Rum",
      "Vodka",
      "Champagne",
      "Cashew",
      "Walnut",
      "Pistachio",
      "Almond",
      "Coffee",
      "Tea",
    ],
  },
];
